### ISSUE TITLE
more information

### ISSUE THREAD

**Issue by HHIR** [Finspire13/RL-Surgical-Gesture-Segmentation#1]
Dear @Finspire13 

could you please, share the abstract of the article?

Thank you

**Comment by Finspire13** [comment]
Sure. Please find below:

*Abstract. Recognition of surgical gesture is crucial for surgical skill
assessment and efficient surgery training. Prior works on this task are
based on either variant graphical models such as HMMs and CRFs, or deep
learning models such as Recurrent Neural Networks and Temporal
Convolutional Networks. Most of the current approaches usually suffer from
over-segmentation and therefore low segment-level edit scores. In contrast,
we present an essentially different methodology by modeling the task as a
sequential decision-making process. An intelligent agent is trained using
reinforcement learning with hierarchical features from a deep model.
Temporal consistency is integrated into our action design and reward
mechanism to reduce over-segmentation errors. Experiments on JIGSAWS
dataset demonstrate that the proposed method performs better than
state-of-the-art methods in terms of the edit score and on par in
frame-wise accuracy. Our code will be released later. *


Hossein Hashemi <notifications@github.com> 于2018年6月17日周日 下午10:58写道：

**Comment by Finspire13** [comment]
Can I have your personal email?

Daochang Liu <finspire13@gmail.com> 于2018年6月17日周日 下午11:17写道：

**Comment by Finspire13** [comment]
@Hosseinhashemiir Can I have your email?

**Comment by HHIR** [comment]
@Finspire13  for sure. 

[To prevent spam robots. The email address has been deleted.]
Thank you for your kindly attention.

**Comment by Finspire13** [comment]
https://arxiv.org/abs/1806.08089
