### ISSUE TITLE
如果将该模型用于歌词生成怎么样?

### ISSUE THREAD

**Issue by tine8899** [Finspire13/RL-Surgical-Gesture-Segmentation#3]
你们把 TCN 和 RL 结合在了一起。如果我打算用来做歌词生成 RL 的 reward action state 这些设计有什么建议吗？谢谢

**Comment by tine8899** [comment]
实现方面 TCN 为什么要用 LSTM 来实现，我看 https://github.com/locuslab/TCN/tree/master/TCN 这里实现没用 LSTM.

**Comment by Finspire13** [comment]
1. 不好意思，我对歌词生成的任务不太熟悉；
2. 当初尝试了一下将TCN和LSTM结合起来，因此代码里面留有一些LSTM。最终使用的TCN模型不包括LSTM。

lyricslee <notifications@github.com> 于2019年2月11日周一 上午3:17写道：
